# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image:
  name: atlassianlabs/docker-node-jdk-chrome-firefox:latest
  run-as-user: 1000

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npx lerna bootstrap
          - npx lerna run clean
          - npx lerna run lint:ci
          - npx lerna run test:ci
          - npx lerna run build:ci
          - npx lerna run docs
