# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.

# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassianlabs/docker-node-jdk-chrome-firefox:latest

options:
  max-time: 5 # minutes

pipelines:
  default:
    - step:
        name: Lint, Test and Build
        caches:
          - node
        script:
          - npm install
          - npx lerna bootstrap
          - npx lerna run lint:ci
          - npx lerna run test:ci
          - npx lerna run build:ci
          - npx lerna run docs
