image: atlassianlabs/docker-node-jdk-chrome-firefox:latest
options:
  max-time: 10 # minutes
definitions:
  caches:
    sonar: ~/.sonar/cache
  steps:
    - step: &validate
        name: Validate
        caches:
          - node
        script:
          - npm install --unsafe-perm
          - npm run lint:ci
          - npm run test:ci
          - npm run sonar:ci-eslint
          - npm run sonar:ci-stylelint
        artifacts:
          - reports/**
          - base-app/reports/**
          - base-service-worker/reports/**
          - tenants/*/reports/**
    - step: &build
        name: Build
        caches:
          - node
        script:
          - npm install --unsafe-perm
          - npm run build:ci
        artifacts:
          - tenants/*/deploy/**
    - step: &build-gated
        name: Quality Gate, then Build
        caches:
          - node
          - sonar
        clone:
          depth: full
        script:
          - pipe: sonarsource/sonarcloud-scan:0.1.5
            variables:
              SONAR_TOKEN: ${SONAR_TOKEN}
          - npm install --unsafe-perm
          - npm run build:ci
        artifacts:
          - tenants/*/deploy/**
pipelines:
  pull-requests:
    '**':
      - step: *validate
      - step: *build-gated
      - step:
          name: Deploy to testing
          deployment: test
          script:
            - echo PR-${BITBUCKET_PR_ID}
            - pipe: atlassian/ssh-run:0.1.4
              variables:
                SSH_USER: ${DEPLOY_USER}
                SERVER: ${DEPLOY_WEBSERVER}
                COMMAND: 'cd ${DEPLOY_DOC_ROOT} && rm -rf PR-${BITBUCKET_PR_ID} && mkdir -p PR-${BITBUCKET_PR_ID}'
            - pipe: atlassian/sftp-deploy:0.4.0
              variables:
                USER: ${DEPLOY_USER}
                SERVER: ${DEPLOY_WEBSERVER}
                REMOTE_PATH: '${DEPLOY_DOC_ROOT}/PR-${BITBUCKET_PR_ID}'
                LOCAL_PATH: 'tenants/*/deploy/*'
            - pipe: atlassian/ssh-run:0.1.4
              variables:
                SSH_USER: ${DEPLOY_USER}
                SERVER: ${DEPLOY_WEBSERVER}
                COMMAND: 'cd ${DEPLOY_DOC_ROOT}/PR-${BITBUCKET_PR_ID} && for f in *.zip; do unzip \$f -d \${f%.zip}; done'
  branches:
    master:
      - step: *validate
      - step: *build-gated
      - step:
          name: Deploy to staging
          deployment: staging
          script:
            - pipe: atlassian/ssh-run:0.1.4
              variables:
                SSH_USER: ${DEPLOY_USER}
                SERVER: ${DEPLOY_WEBSERVER}
                COMMAND: 'cd ${DEPLOY_DOC_ROOT} && rm -rf staging && mkdir -p staging'
            - pipe: atlassian/sftp-deploy:0.4.0
              variables:
                USER: ${DEPLOY_USER}
                SERVER: ${DEPLOY_WEBSERVER}
                REMOTE_PATH: '${DEPLOY_DOC_ROOT}/staging'
                LOCAL_PATH: 'tenants/*/deploy/*'
            - pipe: atlassian/ssh-run:0.1.4
              variables:
                SSH_USER: ${DEPLOY_USER}
                SERVER: ${DEPLOY_WEBSERVER}
                COMMAND: 'cd ${DEPLOY_DOC_ROOT}/staging && for f in *.zip; do unzip \$f -d \${f%.zip}; done'
      - step:
          name: Deploy to production
          deployment: production
          trigger: manual
          script:
            - pipe: atlassian/ssh-run:0.1.4
              variables:
                SSH_USER: ${DEPLOY_USER}
                SERVER: ${DEPLOY_WEBSERVER}
                COMMAND: 'cd ${DEPLOY_DOC_ROOT} && rm -rf production && mkdir -p production'
            - pipe: atlassian/sftp-deploy:0.4.0
              variables:
                USER: ${DEPLOY_USER}
                SERVER: ${DEPLOY_WEBSERVER}
                REMOTE_PATH: '${DEPLOY_DOC_ROOT}/production'
                LOCAL_PATH: 'tenants/*/deploy/*'
            - pipe: atlassian/ssh-run:0.1.4
              variables:
                SSH_USER: ${DEPLOY_USER}
                SERVER: ${DEPLOY_WEBSERVER}
                COMMAND: 'cd ${DEPLOY_DOC_ROOT}/production && for f in *.zip; do unzip \$f -d \${f%.zip}; done'
