name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, lint, and test
      run: |
        npm install
        npm run lint:ci
        npm run test:ci
      env:
        CI: true
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: npm install, build, and test
      run: |
        npm run docs:ci
        npm run build:ci
      env:
        CI: true
