name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, lint, and test
      run: |
        npm install
        npm run lint:ci
        npm run test:ci
        npm run sonar:ci-eslint
        npm run sonar:ci-stylelint
        find reports -type f -name '*.json' | xargs sed -i 's+/home/runner/work/edu.schwabe.multi-tenancy-webapp/edu.schwabe.multi-tenancy-webapp+/github/workspace+g'
        find {apps,libs}/*/reports -type f -name 'lcov.info' | xargs sed -i 's+/home/runner/work/edu.schwabe.multi-tenancy-webapp/edu.schwabe.multi-tenancy-webapp+/github/workspace+g'
      env:
        CI: true
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: generate docs and build artifacts
      run: |
        npm run docs:ci
        npm run build:ci
      env:
        CI: true
